apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yb-data-service
  # the namespace the argocd belongs to
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    # The namespace the application belongs to.
    namespace: argocd
  source:
    repoURL: 'https://github.com/vmeet24/yb-eks'
    path: multi-tenant
    targetRevision: HEAD
    directory:
      recurse: true    
  # The project the application belongs to.
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true