---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-yb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-bot
  namespace: gitops-yb
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-yb-sz
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yb-sz-bot-role
  namespace: gitops-yb-sz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: gitops-bot
  namespace: gitops-yb