apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yb-sz
  # namespace should point to argocd's controller namespace
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-yb-sz
  source:
    path: yb
    repoURL: 'https://github.com/vmeet24/yb-eks'
    targetRevision: HEAD    
    helm:
      parameters:
        - name: replicas.master
          value: '1'
        - name: replicas.tserver
          value: '1'
        - name: storage.master.count
          value: '1'
        - name: storage.tserver.count
          value: '1'
        - name: resource.master.requests.cpu
          value: '500m'
        - name: resource.tserver.requests.cpu
          value: '2'
        - name: gflags.master.placement_cloud
          value: 'ybcloud'
        - name: gflags.master.placement_region
          value: 'pandora'
        - name: gflags.master.placement_zone
          value: 'az'
        - name: gflags.tserver.placement_cloud
          value: 'ybcloud'
        - name: gflags.tserver.placement_region
          value: 'pandora'
        - name: gflags.tserver.placement_zone
          value: 'az'
        - name: Image.tag
          value: '2024.1.3.0-b105'
        - name: storage.master.storageClass
          value: 'yb-storage'
        - name: storage.tserver.storageClass
          value: 'yb-storage'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true