# apiVersion: batch/v1
# kind: Job
# metadata:
#   generateName: yb-cluster-config-
#   namespace: infra-test
#   annotations:
#     argocd.argoproj.io/hook: PostSync
#     argocd.argoproj.io/hook-delete-policy: HookSucceeded
# spec:
#   template:
#     spec:
#       serviceAccount: gitops-bot
#       containers:
#       - name: config-job
#         image: portainer/kubectl-shell
#         command:
#           - '/bin/sh'
#           - '-c'
#           - |        
#               APISERVER=https://kubernetes.default.svc
#               SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
#               NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
#               TOKEN=$(cat ${SERVICEACCOUNT}/token)
#               CACERT=${SERVICEACCOUNT}/ca.crt
#               kubectl config set-cluster yb --server=$APISERVER --certificate-authority=$CACERT
#               kubectl config set-context yb --cluster=yb --user=default
#               kubectl config set-credentials default --token=$TOKEN --user=default
#               kubectl config use-context yb
#               RF=3
#               wt=5
#               while true
#               do
#                 if [ $(nc -z -w 1 yb-master-yugabyte-yb-master-0.yb-master-yugabyte-yb-masters.infra-test.svc.cluster.local:7100; echo $?) -eq 0 -a \
#                      $(nc -z -w 1 yb-master-yugabyte-yb-master-1.yb-master-yugabyte-yb-masters.infra-test.svc.cluster.local:7100; echo $?) -eq 0 -a  \
#                      $(nc -z -w 1 yb-master-yugabyte-yb-master-2.yb-master-yugabyte-yb-masters.infra-test.svc.cluster.local:7100; echo $?) -eq 0 ]; then
#                   echo "instance seems up; applying the config change"
#                   kubectl exec -n infra-test yb-master-yugabyte-yb-master-0 -c yb-master -- bash -c "/home/yugabyte/master/bin/yb-admin --master_addresses yb-master-yugabyte-yb-master-0.yb-master-yugabyte-yb-masters.infra-test.svc.cluster.local:7100,yb-master-yugabyte-yb-master-1.yb-master-yugabyte-yb-masters.infra-test.svc.cluster.local:7100,yb-master-yugabyte-yb-master-2.yb-master-yugabyte-yb-masters.infra-test.svc.cluster.local:7100 modify_placement_info aws.tenant-master.node-master,aws.tenant-master.node-master,aws.tenant-master.node-master $RF"
#                   if [ $? -eq 0 ]; then 
#                     echo "successfully applied config change"
#                     break
#                   fi
#                 fi
#                 echo "instance is not ready yet; ${wt}s sleep before retry"
#                 sleep $wt
#               done
#       restartPolicy: Never
#   backoffLimit: 3
#   # 10m deadline to wait for the image download 
#   activeDeadlineSeconds: 600